##### Create a NumPy array representing daily rainfall (mm) for 30 days, with random values between 0 and 100

In [6]:
import numpy as np
rainfall= np.random.uniform(0,100,30) 
rainfall
# unform is used for fair chance. i mean if uniform is not used it can gice output as 0.1,0.2...thats wrong as it is focusing to 0...with uniform it can give 0.1,4.5,8.9,etc

array([53.77409646, 67.52526572, 69.10686544, 40.04204049, 19.78090066,
       59.98201861, 10.58778968, 29.59958583, 77.03796957, 40.77993336,
       88.41296443, 54.56425713, 98.83590816, 83.58955054, 73.56860632,
       62.62858516, 75.37187954, 38.41457913, 67.21668783, 67.34805139,
        9.55318139, 37.85564825,  7.80029517, 77.98114468, 19.85226866,
       80.71885425, 42.3870325 , 37.76393659, 39.53875338, 81.74599981])

##### Generate a 12×5 array representing monthly sales for 5 stores, and calculate total yearly sales per store

In [8]:
sales = np.random.randint(50000, 200000, size=(12, 5))
ans = np.sum(sales , axis=0)
ans

array([1251376, 1413982, 1279582, 1574227, 1630421])

#####  Create an array of timestamps for each hour of a day (24 values) using np.arange and multiplyby random energy-consumption data.

In [12]:
timestamps = np.arange(1,25)
energy = np.random.randint(10,50, size=24)
ans =timestamps*energy
ans

array([ 29,  56,  90,  48, 115, 156, 294, 368, 414, 490, 176, 168, 637,
       322, 315, 352, 238, 738, 475, 720, 777, 242, 483, 960])

##### From your rainfall data array, extract readings from day 10 to day 20

In [13]:
extracted = rainfall[10:21]
extracted

array([88.41296443, 54.56425713, 98.83590816, 83.58955054, 73.56860632,
       62.62858516, 75.37187954, 38.41457913, 67.21668783, 67.34805139,
        9.55318139])

##### From a 7×24 temperature matrix, get day 3 & evening hours 18:00–23:00

In [14]:
temp = np.random.uniform(15,40 ,size=(7,24)) 
extract= temp[2,18:24]
extract

array([29.73876518, 23.62914898, 31.5802697 , 24.60594543, 27.77350001,
       39.01662898])

##### Reverse a daily sales array (latest → oldest)

In [15]:
sales = np.random.randint(1000, 5000, size=30)

reversed_sales = sales[::-1]
print(reversed_sales)


[4279 1365 4759 3151 4202 2882 2233 1409 3672 4188 4053 1881 3478 2402
 3430 1152 4286 1975 1559 1278 2582 1618 2040 1845 1952 3111 3844 2548
 3126 2374]


##### Extract only the top 10 rainfall readings from the dataset using slicing after sorting.

In [16]:
rain_sort = np.sort(rainfall)

In [18]:
top_10= rain_sort[-10:]
top_10

array([69.10686544, 73.56860632, 75.37187954, 77.03796957, 77.98114468,
       80.71885425, 81.74599981, 83.58955054, 88.41296443, 98.83590816])

##### Replace missing values (np.nan) in your sales data with the mean of that column

In [19]:
sales = np.array([12000, 15000, np.nan, 13000, np.nan, 17000])
#Here np.nan means “Not a Number”, representing missing or invalid data.
#If you use np.mean() directly, it will return nan (because missing values spoil the mean).
#So we use:
mean_value = np.nanmean(sales)
#Step 3 — Replace missing values with the mean
sales_filled = np.where(np.isnan(sales), mean_value, sales)
sales_filled

array([12000., 15000., 14250., 13000., 14250., 17000.])